import { useEffect, useState } from 'react'
import { ListChecks, Plus, Trash2, X } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Checkbox } from '@/components/ui/checkbox'
import EmptyState from '@/components/ui/EmptyState'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { useI18n } from '@/lib/i18n'
import { codify } from '@/domain/shared/slugify'

import type { Attribute } from '../types'
import { NEW_ID } from '../types'

interface AttributeEditorProps {
  selectedAttribute: Attribute | null
  onSelectAttribute: (attr: Attribute | null) => void
  categories?: any[]
  onSaveAttribute?: (attr: Partial<Attribute>) => void
  onDeleteAttribute?: (id: string | number) => void
  loading?: boolean
}

const GENERAL_CATEGORY = 'General'

/** Detail del workspace de atributos: ficha de edición o invitación a seleccionar. */
export function AttributeEditor({
  selectedAttribute,
  onSelectAttribute,
  categories = [],
  onSaveAttribute,
  onDeleteAttribute,
  loading,
}: AttributeEditorProps) {
  const { t } = useI18n()
  const [formData, setFormData] = useState<Partial<Attribute>>({})

  useEffect(() => {
    if (selectedAttribute) {
      setFormData(selectedAttribute)
    }
  }, [selectedAttribute])

  const handleChange = (field: keyof Attribute, value: any) => {
    setFormData((prev) => {
      const newData = { ...prev, [field]: value }
      if (field === 'name' && (!prev.code || prev.id === NEW_ID)) {
        // Autogenerate code if it's a new attribute (snake_case)
        newData.code = codify(String(value))
      }
      return newData
    })
  }

  const handleSave = (e: React.FormEvent) => {
    e.preventDefault()
    if (onSaveAttribute) {
      const payload = { ...formData }
      if (payload.id === NEW_ID) {
        delete payload.id
      }
      onSaveAttribute(payload)
    }
  }

  const handleAddOption = () => {
    setFormData((prev) => ({
      ...prev,
      options: [...(prev.options || []), t('attributes.editor.new_option')],
    }))
  }

  const handleRemoveOption = (index: number) => {
    setFormData((prev) => ({
      ...prev,
      options: (prev.options || []).filter((_, i) => i !== index),
    }))
  }

  const handleOptionChange = (index: number, val: string) => {
    setFormData((prev) => {
      const opts = [...(prev.options || [])]
      opts[index] = val
      return { ...prev, options: opts }
    })
  }

  const isExisting = !!selectedAttribute && selectedAttribute.id !== NEW_ID

  if (!selectedAttribute) {
    return (
      <div className="bg-surface rounded-md shadow-whisper border-0 p-lg h-full">
        <EmptyState
          icon={ListChecks}
          title={t('attributes.editor.empty_title')}
          description={t('attributes.editor.empty_description')}
        />
      </div>
    )
  }

  return (
    <div className="bg-surface rounded-md shadow-whisper border-0 p-lg flex flex-col">
      <div className="flex justify-between items-center mb-md border-b border-border-subtle pb-sm">
        <h3 className="text-title-md text-foreground">{t('attributes.editor.title')}</h3>
        {isExisting ? (
          <Button
            type="button"
            variant="ghost"
            size="icon"
            onClick={() => onDeleteAttribute && onDeleteAttribute(selectedAttribute!.id)}
            disabled={loading}
            aria-label={t('attributes.action.delete')}
          >
            <Trash2 className="w-5 h-5" />
          </Button>
        ) : null}
      </div>

      <form onSubmit={handleSave} className="flex-1 space-y-md">
        <div className="space-y-xs">
          <Label htmlFor="attr-name" className="text-body-md-bold text-foreground">
            {t('attributes.editor.name')}
          </Label>
          <Input
            id="attr-name"
            type="text"
            value={formData.name || ''}
            onChange={(e) => handleChange('name', e.target.value)}
            required
            disabled={loading}
          />
        </div>
        <div className="space-y-xs">
          <Label htmlFor="attr-code" className="text-body-md-bold text-foreground">
            {t('attributes.editor.code')}{' '}
            <span className="text-on-surface-deep font-normal text-body-sm">({t('attributes.editor.code_autogenerated')})</span>
          </Label>
          <Input
            id="attr-code"
            type="text"
            readOnly
            className="bg-surface-muted text-data-mono font-data-mono text-on-surface-deep"
            value={formData.code || ''}
          />
        </div>

        <div className="grid grid-cols-2 gap-sm">
          <div className="space-y-xs">
            <Label htmlFor="attr-type" className="text-body-md-bold text-foreground">{t('attributes.editor.type')}</Label>
            <Select
              value={formData.type || 'STRING'}
              onValueChange={(v) => handleChange('type', v)}
            >
              <SelectTrigger id="attr-type">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="STRING">STRING</SelectItem>
                <SelectItem value="NUMBER">NUMBER</SelectItem>
                <SelectItem value="BOOLEAN">BOOLEAN</SelectItem>
                <SelectItem value="LIST">LIST</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-xs">
            <Label htmlFor="attr-category" className="text-body-md-bold text-foreground">{t('attributes.editor.category')}</Label>
            <Select
              value={formData.category || GENERAL_CATEGORY}
              onValueChange={(v) => handleChange('category', v)}
            >
              <SelectTrigger id="attr-category">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={GENERAL_CATEGORY}>{t('attributes.editor.category_general')}</SelectItem>
                {categories.length > 0 ? (
                  <SelectGroup>
                    <SelectLabel>{t('attributes.editor.categories_product')}</SelectLabel>
                    {categories.map((c: any) => (
                      <SelectItem key={c.id} value={String(c.id)}>{c.name}</SelectItem>
                    ))}
                  </SelectGroup>
                ) : null}
              </SelectContent>
            </Select>
          </div>
        </div>

        {formData.type === 'LIST' ? (
          <div className="bg-surface-muted p-sm rounded-md border border-border-subtle">
            <div className="flex justify-between items-center mb-sm">
              <Label className="text-body-md-bold text-foreground">{t('attributes.editor.list_options')}</Label>
              <Button type="button" variant="ghost" size="sm" onClick={handleAddOption} className="text-primary">
                <Plus className="w-4 h-4 mr-xs" />
                {t('attributes.editor.add_option')}
              </Button>
            </div>
            <div className="space-y-sm">
              {(formData.options || []).map((opt, i) => (
                <div key={i} className="flex items-center gap-sm">
                  <Input
                    className="flex-1"
                    type="text"
                    value={opt}
                    onChange={(e) => handleOptionChange(i, e.target.value)}
                    aria-label={`${t('attributes.editor.list_options')} ${i + 1}`}
                  />
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    onClick={() => handleRemoveOption(i)}
                    aria-label={t('attributes.editor.remove_option')}
                  >
                    <X className="w-4 h-4" />
                  </Button>
                </div>
              ))}
              {(!formData.options || formData.options.length === 0) ? (
                <p className="text-body-md text-on-surface-deep">{t('attributes.editor.no_options')}</p>
              ) : null}
            </div>
          </div>
        ) : null}

        <div className="grid grid-cols-2 gap-y-sm gap-x-md pt-sm border-t border-border-subtle">
          <label className="flex items-center gap-sm cursor-pointer">
            <Checkbox
              checked={!!formData.isRequired}
              onCheckedChange={(checked) => handleChange('isRequired', checked === true)}
            />
            <span className="text-body-md text-foreground">{t('attributes.editor.required')}</span>
          </label>
          <label className="flex items-center gap-sm cursor-pointer">
            <Checkbox
              checked={!!formData.isFilterable}
              onCheckedChange={(checked) => handleChange('isFilterable', checked === true)}
            />
            <span className="text-body-md text-foreground">{t('attributes.editor.filterable')}</span>
          </label>
          <label className="flex items-center gap-sm cursor-pointer">
            <Checkbox
              checked={formData.isVisible !== false}
              onCheckedChange={(checked) => handleChange('isVisible', checked === true)}
            />
            <span className="text-body-md text-foreground">{t('attributes.editor.visible')}</span>
          </label>
          <label className="flex items-center gap-sm cursor-pointer" title={t('attributes.editor.variant_hint')}>
            <Checkbox
              checked={!!formData.isVariant}
              onCheckedChange={(checked) => handleChange('isVariant', checked === true)}
            />
            <span className="text-body-md text-foreground">{t('attributes.editor.variant')}</span>
          </label>
        </div>

        <div className="pt-md border-t border-border-subtle flex justify-end gap-sm">
          <Button
            type="button"
            variant="secondary"
            onClick={() => onSelectAttribute(null)}
            disabled={loading}
          >
            {t('common.cancel')}
          </Button>
          <Button type="submit" variant="primary" loading={loading}>
            {t('common.save')}
          </Button>
        </div>
      </form>
    </div>
  )
}

export default AttributeEditor
