/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        'xs': '480px',
      },
      transitionDuration: {
        '1500': '1500ms',
        '2000': '2000ms',
        '2500': '2500ms',
      },
      colors: {
        primary: {
          DEFAULT: "#137fec", // Stitch Primary
          hover: "#0f67be",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Stitch design specific colors
        surface: "hsl(var(--surface))",
        text: {
          main: "hsl(var(--text-main))",
          secondary: "hsl(var(--text-secondary))",
        },
        border: {
          subtle: "hsl(var(--border-subtle))",
        },
        success: "#107c10",
        error: "#c50f1f",
        warning: "#d83b01",
        "background-light": "#f0f2f5",
        "background-dark": "#101922",
        "surface-light": "#ffffff",
        "surface-dark": "#1a2633",
        "text-primary-light": "#111418",
        "text-secondary-light": "#617589",
        "text-primary-dark": "#f0f2f4",
        "text-secondary-dark": "#9ba6b5",
        "semantic-success": "#107c10",
        "semantic-danger": "#c50f1f",
        "semantic-warning": "#d83b01",
        "fluent-success": "#107c10",
        "fluent-danger": "#d13438",
        "fluent-warning": "#ffaa44",
        "fluent-gray": "#f3f2f1",
        // Stitch full colors
        "tertiary-fixed-dim": "#ffb68c",
        "inverse-primary": "#a8c8ff",
        "inverse-on-surface": "#eef1f9",
        "surface-tint": "#005eb4",
        "outline": "#717785",
        "secondary": "#455f89",
        "on-primary-fixed": "#001b3c",
        "secondary-container": "#b3cdfd",
        "on-secondary-container": "#3c5780",
        "tertiary": "#964400",
        "outline-variant": "#c1c6d5",
        "on-secondary-fixed": "#001b3c",
        "on-background": "#181c22",
        "on-surface": "#181c22",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdbc9",
        "inverse-surface": "#2d3137",
        "background": "#f8f9ff",
        "on-tertiary-container": "#fffbff",
        "on-tertiary-fixed": "#321200",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#2c4770",
        "on-primary-container": "#fefcff",
        "primary-fixed-dim": "#a8c8ff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d6e3ff",
        "primary-container": "#0074db",
        "on-primary": "#ffffff",
        "tertiary-container": "#bc5700",
        "surface-container": "#ebeef6",
        "primary": "#005baf",
        "on-tertiary-fixed-variant": "#753400",
        "on-surface-variant": "#414753",
        "surface-container-high": "#e5e8f1",
        "surface-container-low": "#f1f3fc",
        "surface-dim": "#d7dae2",
        "on-primary-fixed-variant": "#004689",
        "surface-container-highest": "#dfe2eb",
        "secondary-fixed-dim": "#adc7f7",
        "primary-fixed": "#d5e3ff",
        "on-error": "#ffffff",
        "surface-variant": "#dfe2eb",
        "error": "#ba1a1a",
        "surface": "#f8f9ff",
        "surface-bright": "#f8f9ff"
      },
      spacing: {
        "xl": "48px",
        "sm": "8px",
        "gutter": "24px",
        "base": "4px",
        "lg": "24px",
        "container-max": "1440px",
        "md": "16px",
        "xs": "4px",
        "margin-page": "40px"
      },
      fontFamily: {
        "sans": ["Inter", "Public Sans", "system-ui", "sans-serif"],
        "display": ["Inter", "system-ui", "sans-serif"],
        "montserrat": ["Montserrat", "sans-serif"],
        "public": ["Public Sans", "sans-serif"],
        "mono": ["Source Code Pro", "monospace"],
        "ibm": ["IBM Plex Mono", "monospace"],
        "tabular": ["Source Code Pro", "monospace"],
        "data-mono": ["Source Code Pro", "monospace"],
        "data-tabular": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-md-bold": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-sm-bold": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      borderRadius: {
        xl: "8px",
        lg: "6px",
        md: "4px",
        sm: "2px",
      },
      boxShadow: {
        "fluent-2": "0 2px 4px rgba(0,0,0,0.04), 0 0 2px rgba(0,0,0,0.06)",
        "fluent-8": "0 4px 8px rgba(0,0,0,0.12), 0 0 2px rgba(0,0,0,0.06)",
        "fluent-16": "0 8px 16px rgba(0,0,0,0.14), 0 0 2px rgba(0,0,0,0.06)",
        "fluent-shadow": "0 2px 4px rgba(0,0,0,0.04), 0 4px 8px rgba(0,0,0,0.04)",
        "card": "0 2px 4px rgba(0,0,0,0.04), 0 0 2px rgba(0,0,0,0.06)",
      },
      fontSize: {
        "title-md": ["18px", { "lineHeight": "24px", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "900" }],
        "data-table": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "data-tabular": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "900" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-md-bold": ["16px", { "lineHeight": "24px", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-sm-bold": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "900" }]
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
}

