name: E2E Playwright

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright browsers
        run: pnpm exec playwright install
      - name: Start dev server
        run: pnpm dev &
      - name: Wait for server
        run: npx wait-on http://localhost:5173 -t 120000
      - name: Run Playwright tests (including AXE)
        run: pnpm exec playwright test --project=chromium --reporter=list
      - name: Upload Playwright report (if generated)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report || ''
      - name: Upload JUnit results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: junit-report.xml || ''
